config/routes.rb
Rails.application.routes.draw do
 

  resources :users do
    member do
     get 'manage'
     get 'moderator_invitations'
     get 'my_clubs'
    end
  end
  
  
  resources :member_requests, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :clubs, only: [:new, :create, :index, :edit, :update]
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end

  root 'welcome#welcomepage'
  
  get 'welcome/home'
  get 'welcome/terms'
  get 'welcome/map'
  get 'welcome/privacy'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/help'
  get 'signup' =>'user#new'

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

 

  
  get 'commit' => 'clubs#new'
  get 'p/:path' => 'clubs#show', as: :view_club
  get 'p/:path/manage/members' => 'clubs#show_members', as: :manage_club_members
  get 'p/:path/manage/manage_requests' => 'clubs#manage_requests', as: :manage_requests
  get 'p/:path/manage' => 'clubs#manage', as: :manage_club
  get 'p/:path/manage/add_moderator' => 'clubs#add_moderator', as: :add_moderator_club
  post 'p/:path/manage/mod_request' => 'clubs#mod_request', as: :mod_request_club
  post 'p/:path/update_modrequest' => 'clubs#update_modrequest', as: :update_modrequest_club
  
  get 'p/:path/newpost' => 'posts#new', as: :new_club_post
  get 'p/:path/:post_id' => 'posts#show', as: :view_club_post

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessor :remove_bg, :remove_banner
  
  belongs_to :user
  has_many :moderators,through: :moderations
  has_many :moderations
  has_many :posts
  has_many :members, through: :memberships
  has_many :memberships
  has_many :requesting_users, through: :member_requests
  has_many :member_requests
  
  after_create :make_owner_mod
  after_create :make_owner_member
  #after_create :downcase_path
  before_save :set_club_path
  before_save :delete_background, if: -> {remove_bg == '1' && !background_updated_at_changed?}
  before_save :delete_banner, if: -> {remove_banner == '1' && !banner_updated_at_changed?}
  
  has_attached_file :club_avatar, :styles => { :medium => "400x400>", :thumb => "320x320#" }, :default_url => "missing.jpg"
  validates_attachment_content_type :club_avatar, :content_type => /\Aimage\/.*\Z/
 
  
  validates :name,  presence: true, length: { maximum: 70 },
                        uniqueness: { case_sensitive: false }
  validates :description,  presence: true, length: { maximum: 1000 }

  #validates :user_id, presence: true

  
  
  has_attached_file :background, styles: { :medium => "300x300>", large: "1024x768>" }
  validates_attachment_content_type :background, :content_type => /\Aimage\/.*\Z/

  has_attached_file :banner, styles: { :medium => "300x300>", large: "1024x768>" }
  validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/
  
  
  
  
  def self.by_path(path)
    Club.where('path=?', path).first
  end
  
  def is_member?(user)
    members.include?(user)
  end
  
  def is_owner?(user)
    user.id == user_id
  end
  
  def is_moderator?(user)
    moderators.include?(user)
  end
  
  def add_moderator!(new_moderator)
    Moderation.create!(user_id: new_moderator.id, club_id: id)
  end

#user ILIKE for PostgrSQL

  def self.search(search)
    where 'name LIKE :search OR description LIKE :search OR genre LIKE :search', :search => "%#{search}%"
  end
  
  #def order(order)
   # @clubs = Club.find(:all)
  #end
    
 
  private
  
  def downcase_path
    self.path = path.downcase
  end
  
  def set_club_path
    self.path = name  
    self.path = path.downcase
  end
  
  def make_owner_mod
    Moderation.create!(user_id: user_id, club_id: id)
  end
  
  def make_owner_member
    Membership.create!(user_id: user_id, club_id: id)
  end
  
  def delete_background
    self.background = nil
  end 
  
  def delete_banner
    self.banner = nil
  end 
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :logged_in_user, except: [:show, :index]
    before_action :find_club_path, only: [:show, :manage, :show_members, :manage_requests, :add_moderator, :mod_request, :update_modrequest]
    before_action :set_club, only: [:edit, :update]
    before_action :admin_only, only: [:new, :create]
    layout 'club' , except: :index
    #before_action :can_moderate?,     only: [:manage, :edit]
    
    def index
        #@clubs = Club.all
        @clubs = Club.all.paginate(page: params[:page], :per_page => 10)
        if params[:search]
            @clubs = Club.search(params[:search]).paginate(page: params[:page])
        #elsif params[:sort].present?
            #@clubs = Club.sort(params[:sort]).paginate(page: params[:page])
        else
            #@clubs = Club.all.paginate(page: params[:page], :per_page => 5)
            @clubs = Club.order(:name).paginate(page: params[:page], :per_page => 5)
           
        end
            
    end

    def new 
        @club = Club.new
    end
    
    def create
        @club = current_user.clubs.build(club_params)
        if @club.save
                flash[:success] = "Club Created" 
                #redirects to club homepage
                redirect_to manage_club_path(path: @club.path)
        else
            render 'new'
        end
    end
    
    # show by likes
    def show
        @posts = @club.posts.by_hot_score.latest.five_days_ago.paginate(page: params[:page])
        @moderators = @club.moderators
    end
    
    def manage
        unless @club.is_moderator?(current_user)
            flash[:danger] = "You are not a moderator of this club" 
            redirect_to build_club_path(@club)
        end
        
        @member_requests = @club.member_requests 
    end
    
    def edit
        unless @club.is_moderator?(current_user)
            flash[:danger] = "You are not a moderator of this club" 
            redirect_to build_club_path(@club)
        end

    end
    
    def update
        #params[:club][:remove_bg] == '1' ? @club.background = nil : @club.background
        
        if @club.update(club_params)
            flash[:success] = "Club Updated!" 
            redirect_to build_club_path(@club)
        else
            render :edit
        end
    end
    
    # shows all members that belong in the club
    def show_members 
        #@users = @club.members
        unless @club.is_moderator?(current_user)
            flash[:danger] = "You are not a moderator of this club" 
            redirect_to build_club_path(@club)
        end
        
        @users = User.all
    end
    
    # manage membership requests
    def manage_requests
        
        unless @club.is_moderator?(current_user)
            flash[:danger] = "You are not a moderator of this club" 
            redirect_to build_club_path(@club)
        end
        
        @member_requests = @club.member_requests
    end
    
    # view where the moderators can add new moderators to their club
    # the new function for moderator invitations
    def add_moderator
        unless @club.is_moderator?(current_user)
            flash[:danger] = "You are not a moderator of this club" 
            redirect_to build_club_path(@club)
        end
        
        @mod_request = ModRequest.new
    end
    
    # the create function for moderator invitations
    def mod_request
        @user = User.by_username_insensitive(params[:username])
        
        #function must exit if user is not found, hence the return
        if @user.nil?
            flash[:danger] = "User does not exist!" 
            redirect_to(:back) and return 
        end
        
        if @club.is_moderator?(@user)
            flash[:danger] = "User is already a moderator of this club" 
            redirect_to(:back) and return 
        end
        
         @mod_request = ModRequest.new(
          #target user
          user_id: @user.id,
          inviting_user_id: current_user.id,
          club_id: @club.id
        )
        
        if @mod_request.save
            flash[:success] = "Moderator request has been sent!"
            redirect_to :back
        else
            flash[:danger] = "Could not send a request at this time, try again later" 
            redirect_to :back
        end
    end
    
    # the update/destroy function for moderator invitations
    def update_modrequest
        
        @mod_request = ModRequest.where(user_id: current_user.id, club_id: @club.id)
                   .first
                   
        if @mod_request.nil?
          flash[:danger] = "Could not find moderator request." 
          redirect_to(:back) and return
        end
        
        #if the user is not a member, make him a member
        if @club.is_moderator?(current_user)
            flash[:danger] = "You are already a moderator of this club."
            redirect_to build_club_path(@club) and return
        end
        
        unless @club.is_member?(current_user)
          Membership.create!(user_id: current_user.id, club_id: @club.id)
        end
        
        @club.add_moderator!(current_user)
        
        @mod_request.destroy
        redirect_to build_club_path(@club)
    end
    
    
    private
    def club_params
        params.require(:club).permit(:name, :description, :path, :genre, :club_avatar, :background, :banner, :remove_bg, :remove_banner)
    end
    
    def find_club_path
        @club = Club.by_path(params[:path])
        
        if @club.nil?
            flash[:danger] = "Unable to find the specified club" 
            redirect_to clubs_path
        end
    end
    
    def set_club
        @club = Club.find(params[:id])
        
        if @club.nil?
            flash[:danger] = "Unable to find the specified club" 
            redirect_to clubs_path
        end
    end
    
    def admin_only
      unless current_user.admin?
        flash[:danger] = "Admin only function."
        redirect_to(root_url)
      end
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
  #def build_club_path(club)
    #view_club_path(path: club.path)
  #end
    # Returns the Gravatar for the given user.
  def gravatar_forc(club, options = { size: 120 })
    gravatar_id = Digest::MD5::hexdigest(club.name)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: club.name, class: "gravatar")
  end
  

  
end

app/views/clubs/_design.html.erb
<%= form_for(@club) do |f| %>
      <%= render 'shared/error_messages',object: f.object %>
   

      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: 'form-control', rows: "5" %>
      
      <%= f.label :club_avatar, "Avatar"  %>
      <%= f.file_field :club_avatar %>
      
      
      <%= f.label :background, "Club Background" %>
      <%= f.file_field :background %>
      
      <%= f.label :banner, "Club Banner" %>
      <%= f.file_field :banner %>
      
      <% if @club.background? %>
            <%= f.label :remove_bg, class: "checkbox inline" do %>
            <%= f.check_box :remove_bg %>
                      &nbsp; &nbsp; Remove Background
            <% end %>
      <% end %>
      
      <% if @club.banner? %>
            <%= f.label :remove_banner, class: "checkbox inline" do %>
            <%= f.check_box :remove_banner %>
                      &nbsp; &nbsp; Remove Banner
            <% end %>
      <% end %>
      
      <%= f.submit "Commit Update", class: "btn btn-primary" %>
<% end %>

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
      <%= render 'shared/error_messages',object: f.object %>
    
      
      <%= f.label :club_avatar, "Avatar"  %>
    
      <%= f.file_field :club_avatar %>
      
      
      <%= f.label :name, "Club's Name" %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: 'form-control', rows: "5" %>
    
      <%= f.label :genre %>
      <%= f.select(:genre, options_for_select([['Arts','Arts'],
                              ['Career Development', 'Career Development'], ['Charitable', 'Charitable'], 
                              ['Cultural', 'Cultural'], ['Other', 'Other'], ['Political', 'Political'],
                              ['Social', 'Social'], ['Social Justice/Activism', 'Social Justice/Activism'],
                              ['Special Interst/Hobby', 'Special Interst/Hobby'], ['Sport', 'Sport'],
                              ['Spiritual', 'Spiritual']])) %>
      
      
     
      
      <%= f.submit "Create New Club", class: "btn btn-primary" %>
    <% end %>

app/views/clubs/_modform.html.erb
<%= form_for(@mod_request, :url => mod_request_club_path(:path => @club.path)) do |f| %>

  <%= label_tag :username %><br>
  <%= text_field_tag :username %>
  
  <br/><i>Enter the username of the user who you'd like to add as a moderator.</i>

  <%= f.submit "Add Moderator", class: 'btn btn-primary' %>

<% end %>

app/views/clubs/_sidebar.html.erb
<div class = "box panel panel-default">
    <div class = "sidebar">
        <div id="top-link-block">
            <span class="well well-sm">
                <i class="glyphicon glyphicon-chevron-left"></i> <%= link_to "Back to Clubs" , clubs_path %>
            </span>
        </div>
      <br>
      <br>
      
      
        <% if logged_in? %>
          <!-- Check if the user is already a member if yes then do unsubscribe else subscribe -->
          <% if current_user.memClubs.include?(@club) %> 
          <span style="margin-right: -1px">
            <%= link_to "New Post", new_club_post_path , class: 'btn btn-success'  %>
            </span>
              <!--If current user is not a mod , then show the unsubscribe button-->
           
              <% unless @club.is_moderator?(current_user) %>
                <%= link_to 'Unsubscribe', membership_path(0, club_id: @club.id), method: :delete, data: { confirm: "Are you sure you want to leave?" } , class: 'btn btn-danger' %>
              <% end %>  
          <% else %>
              <%= link_to 'Subscribe', member_requests_path(club_id: @club.id), method: :post, class: 'btn btn-success' %>
          <% end %>
        <% end %>
        <br>
    
        <span style="background-color: #3366ff; color: white; padding: 6px; margin-right: 3px; margin-top: 3px; float: left; border-radius: 4px">
        <span class="glyphicon glyphicon-user"></span>&nbsp;Club Moderators: 
        </span>
        
        
        <% @moderators.each do |moderator| %>
           <% unless moderator.admin? %>
             <span  style="background-color: #ff8433; color: white; padding: 6px; float: left; margin-right: 3px; margin-top: 3px; margin-bottom: 1px; border-radius: 4px"> <%= moderator.name %></span>
           <% end %>
        <%end%>
          
    </div>
</div>

app/views/clubs/add_moderator.html.erb
<div id="top-link-block">
    <span class="well well-sm">
        <i class="glyphicon glyphicon-chevron-left"></i> <%= link_to "Back to Manage Club" , manage_club_path %>
    </span>
</div>

<h1>Add New Moderator</h1>

<div class ="row">
  <div class="col-md-6 col-md-offset-3">  
    <%= render 'modform' %>
    </div>    
</div>

app/views/clubs/edit.html.erb
<div id="top-link-block">
    <span class="well well-sm">
        <i class="glyphicon glyphicon-chevron-left"></i> <%= link_to "Back to Manage Club" , manage_club_path(path: @club.path) %>
    </span>
</div>

<h1>Club Layout Design</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<%= render 'design' %>
</div>
</div>

app/views/clubs/index.html.erb
<% provide(:title, 'All Clubs') %>







	<section id="body" class="width">
		<!--<aside id="sidebar" class="column-left">
    		<header>
    				<h1>Club Directory</h1>
    		</header>
    
                <nav class='verticalmenu'>
                    <ul>
                        <%= form_tag(clubs_path, :method => "get", id: "search-form") do %>
                            <%= text_field_tag :search, params[:search], placeholder: "Search Clubs" %>
                            <%= submit_tag "Search" %>
                        <% end %>

                    </ul>
                </nav>
		</aside>-->
		<section id="content" class="column-right">
    	    <article>
    			<h1>All Clubs</h1>
    			<div class="search_bar">
                <%= form_tag(clubs_path, :method => "get", id: "search-form") do %>
                            <%= text_field_tag :search, params[:search], placeholder: "Search Clubs" %>
                            <%= submit_tag "Search" %>
                <% end %>
                </div>
                <%= will_paginate @clubs %>
    
    
                <% cur_letter = nil %>
                <% @clubs.each do |club| %>
                <% title_letter = club.name[0].capitalize.match(/[A-Z]/) ? club.name[0].capitalize : "#" %>
                <% if title_letter != cur_letter %>
                <% cur_letter = title_letter %>
                <!--<p style="color:black"><%#= cur_letter %>:</p>-->
                <% end %>
                <div class= "clubindex">
                    
                        <%= image_tag(club.club_avatar.url(:thumb)) %>
                       
                        <span>
                        <h3><%= link_to club.name, build_club_path(club) %></h3>
                        
                         
                        Genre: <%= club.genre %>
                        <br>
                        Description:
                        <%= club.description %>
                        
                     </span>
                </div>
                <% end %>
            </article>
               
        </section>
    
    </article>
    		
    </section>
</section>

app/views/clubs/manage.html.erb
<h1 class="headings">
  <%= link_to 'Club Management', manage_user_path(current_user) %> > <%= @club.name %>
</h1>


<div class="management_bar">
     <article>
        
        <h4>
            Pending Requests <span class="badge"><%= @club.member_requests.count %></span></h4>
            <h4><%= link_to "Manage Requests", manage_requests_path %></h4>
        
    </article>
    <article>
        <h4>Manage Club Members <span class="badge"><%= @club.members.count %></span></h4>
        <h4><%= link_to "Show All Members", manage_club_members_path %></h4>
    </article>
    <article>
        <h4> &emsp; </h4>
        <h4><%= link_to "Manage Club Layouts", edit_club_path(@club) %></h4>
        <h4> &emsp; </h4>
    </article>
    <article>
        <h4>Manage Posts <span class="badge"><%= @club.posts.count %></span></h4>
        <% if logged_in? and current_user.memClubs.include?(@club) %>
            <h4><%= link_to "Create new post", new_club_post_path %></h4>
            <h4><%= link_to "See All posts", view_club_path %></h4>
        <% end %>
    </article>
    
    <article>
        <h4> &emsp; </h4>
        <h4><%= link_to "Manage Moderators", add_moderator_club_path %></h4>
        <h4> &emsp; </h4>
    </article>
 
</div>

app/views/clubs/manage_requests.html.erb
<div id="top-link-block">
    <span class="well well-sm">
        <i class="glyphicon glyphicon-chevron-left"></i> <%= link_to "Back to Manage Club" , manage_club_path %>
    </span>
</div>

<h1>Manage Requests</h1>

<table class="profile_ban">
<% if @club.member_requests.count != 0 %>
    <tr>
        <th>Username</th>
        <th>Email</th>
    </tr>
    
<% @member_requests.each do |member_request| %>  
    <p><% user = User.find_by(id: (member_request.user_id)) %>
       <% if @club.is_member?(user) %>
           <!-- Delete Request only if user is a member -->
           <% member_request.destroy %>
           
       <% else %>
        <tr>
            <td><%= link_to user.name, '#' %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Approve', memberships_path(club_id: @club.id, target_user_param: user.id), method: :post, class: 'btn btn-success' %></td>
            <td><%= link_to 'Reject',  member_request_path(0, club_id: @club.id, target_user_param: user.id), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %></td>
        </tr>
       <% end %>
    </p>
<% end %>

<%else%>
There is currently no requests. 
<%end%>


</table>

app/views/clubs/new.html.erb
<% provide(:title, "New Club") %>


<h1 class="headings">Create New Club</h1>

  <div class="row">    
    <div class="col-md-6 col-md-offset-3">
        <p>
          <%= render 'form' %>
        </p>
    
        <br>
    </div>

  </div>

app/views/clubs/show.html.erb
<% provide(:title, @club.name) %>


<h1 class="headings">
  Welcome to <%= @club.name%>
</h1>

<div id = "posts" class = "transitions-enabled" >
  <%= render 'sidebar' %>
  <% @posts.each do |post| %>
  <% @post = post %>
     <% if @post.option=="isEvent" %>
     <div class = "box panel panel-default" style="border-color: green; border-width: 2px;">
    <%= render 'posts/heading' %>
    </div>
    <%else%>
    <div class = "box panel panel-default">
     <%= render 'posts/heading' %>
     </div>
    <%end%>
  <% end %>
  <br>
</div>




<%= will_paginate @posts %>

app/views/clubs/show_members.html.erb
<% provide(:title, 'All users') %>

<div id="top-link-block">
    <span class="well well-sm">
        <i class="glyphicon glyphicon-chevron-left"></i> <%= link_to "Back to Manage Club" , manage_club_path(path: @club.path) %>
    </span>
</div>


<h1>All Club Members</h1>

<table class="profile_ban">
  <tr>
    <th>Members</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
  <tr>
    <% @users.each do |user| %>
    <% if user.memClubs.include?(@club) %>
    <td><%= link_to user.name, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><% if @club.is_moderator?(user) %>
      Moderator
        <%else%>
            Member</td>
        <%end%>
  </tr>
  <% end %>
<% end %>
</table>

        
    





<%#= will_paginate %>