config/routes.rb
Rails.application.routes.draw do
 

  resources :users do
    member do
     get 'manage'
     get 'moderator_invitations'
     get 'my_clubs'
    end
  end
  
  
  resources :member_requests, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :clubs, only: [:new, :create, :index, :edit, :update]
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end

  root 'welcome#welcomepage'
  
  get 'welcome/home'
  get 'welcome/terms'
  get 'welcome/map'
  get 'welcome/privacy'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/help'
  get 'signup' =>'user#new'

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

 

  
  get 'commit' => 'clubs#new'
  get 'p/:path' => 'clubs#show', as: :view_club
  get 'p/:path/manage/members' => 'clubs#show_members', as: :manage_club_members
  get 'p/:path/manage/manage_requests' => 'clubs#manage_requests', as: :manage_requests
  get 'p/:path/manage' => 'clubs#manage', as: :manage_club
  get 'p/:path/manage/add_moderator' => 'clubs#add_moderator', as: :add_moderator_club
  post 'p/:path/manage/mod_request' => 'clubs#mod_request', as: :mod_request_club
  post 'p/:path/update_modrequest' => 'clubs#update_modrequest', as: :update_modrequest_club
  
  get 'p/:path/newpost' => 'posts#new', as: :new_club_post
  get 'p/:path/:post_id' => 'posts#show', as: :view_club_post

end

app/models/user.rb
class User < ActiveRecord::Base
  
    has_many :clubs
    has_many :modClubs, through: :moderations
    has_many :moderations, dependent: :destroy
    has_many :posts
    has_many :memClubs, through: :memberships
    has_many :memberships, dependent: :destroy
    has_many :mod_requests
    has_many :club_requests, through: :member_requests
    has_many :member_requests
    has_many :comments

    
    attr_accessor :remember_token, :activation_token, :reset_token, :terms
    before_save   :downcase_email
    #before_save   :format_email
    before_create :create_activation_digest
    
  
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "missing.png"
    validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)
    
    
    validates :firstname,  length: { maximum: 30 }
    validates :lastname,  length: { maximum: 30 }
    validates :name,  presence: true, length: { maximum: 20 },
                        uniqueness: { case_sensitive: false }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 },
                        uniqueness: { case_sensitive: false },
                        format: {with: VALID_EMAIL_REGEX}
                      
    validates :phone, length: {maximum: 10}
    
    validates :terms, acceptance: true
                        
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Returns the hash digest of the given string.
#  def self.digest(string)
#    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
#                                                  BCrypt::Engine.cost
#    BCrypt::Password.create(string, cost: cost)
#  end

  # Returns a random token.
#  def self.new_token
#    SecureRandom.urlsafe_base64
#  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
#  def authenticated?(remember_token)
#    return false if remember_digest.nil?
#    BCrypt::Password.new(remember_digest).is_password?(remember_token)
#  end
  
   # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # Find user by username
  def self.by_username_insensitive(name)
    User.where('LOWER(name) = ?', name.downcase).first
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  
  private
  
  # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
    #sets user email before saving
    def format_email
      return if email.include?('@sfu.ca')
      self.email = "#{email}@sfu.ca"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :manage, :moderator_invitations]
  before_action :correct_user,   only: [:edit, :update, :manage, :moderator_invitations]
  before_action :admin_user,     only: :destroy
  

  #def index
    #@users = User.all
    #@users = User.paginate(page: params[:page])
  #end
  
  def show
    @user = User.find(params[:id])
    #@clubs = @user.modClubs
    @clubs = @user.memClubs
    @posts = Post.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       # UserMailer.account_activation(@user).deliver_now
       @user.send_activation_email
       flash[:info] = "Please check your email to activate your account."
       redirect_to root_url
       # equivalent to redirect_to user_url(@user)
       # Handle a successful save.
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  
  def manage
    @user = User.find(params[:id])
    #@clubs = @user.clubs
    @clubs = @user.modClubs
    @posts = Post.all
  end
  
  def my_clubs
    @user = User.find(params[:id])
    @clubs = @user.memClubs
  end
  
  def moderator_invitations
    @user = User.find(params[:id])
    #@user = current_user
    @mod_requests = current_user.mod_requests
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  
  private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :name, :email, :password, :terms,
                            :password_confirmation, :gender, :birthday, :phone, :degree, :major, :avatar)
    end
  
    # Before filters

   
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
     # redirect_to(root_url) unless @user == current_user
     redirect_to(root_url) unless current_user?(@user)
    end
    
     # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
   
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
#  def gravatar_for(user)
#    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
#    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
#    image_tag(gravatar_url, alt: user.name, class: "gravatar")
#  end
  
  # Returns the Gravatar for the given user.
  #def gravatar_for(user, options = { size: 80 })
   # gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   # size = options[:size]
   # gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
   # image_tag(gravatar_url, alt: user.name, class: "gravatar")
  #end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


<%= f.label :name, "User Name" %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email, "Email" %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Password Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

  
<%= f.label :terms, class: "checkbox inline" do %> 
   
<%= f.check_box :terms %>
    I agree to the <%= link_to "Terms", welcome_terms_path %>  and <%= link_to "Policies", welcome_privacy_path %> 
<% end %>
  
  <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_tag(user.avatar.url(:thumb))%>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1 class="headings">Update your profile</h1>
    
    

  <div class="row">
    
    
    <div class="avatar_edit">
        <%= image_tag(current_user.avatar.url(:thumb)) %>
    </div>
    
    
    
    
    <div class="col-md-6 col-md-offset-3">
        <%#<%= render 'form' %>
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
        
       
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
       
 
        
        
          <%= f.label :email, "Email:" %>
          <%= @user.email %>
          <br>
          <%= f.label :name, "Username" %>
          <%= @user.name %>
      
          <br>
          <%= f.label :firstname, "First Name" %>
          <%= f.text_field :firstname, class: 'form-control' %>
          
          <%= f.label :lastname, "Last Name" %>
          <%= f.text_field :lastname, class: 'form-control' %>
        
          
          
          <%= f.label :gender, "Gender" %>
        
            <%#= f.radio_button :gender, true %> <%#= f.label :gender, "Female" %>
            <%#= f.radio_button :gender, false %> <%#= f.label :gende, "Male" %>
   
          <%= f.select(:gender, options_for_select([['Female','♀'],
                              ['Male', '♂']])) %>
          
          <%= f.label :birthday %>
          <%= f.date_select :birthday, :start_year=>1985  %>
          
                              
          <%= f.label :phone, "Phone Number" %>
          <%= f.text_field :phone, class: 'form-control' %>
          
          <%= f.label :degree, "Degree" %>
          <%= f.select(:degree, options_for_select([['1st Year','1st Year'],
                              ['2nd Year', '2nd Year'], ['3rd Year', '3rd Year'],
                              ['4th Year', '4th Year'], ['Master', 'Master'],
                              ['Other', 'Other']])) %>
          
          <%= f.label :major, "Major" %>
          <%= f.text_field :major, class: 'form-control' %>
          
          <%= f.submit "Update Profile", class: "btn btn-primary" %>
        <% end %>
        <br>
    </div>
  
  </div>

app/views/users/manage.html.erb
<div class="row">      
      
<% @user = User.find(params[:id]) %>

    <% if @user.modClubs.any? %>
    <div class="profile_ban">
        <h1>Manage your Clubs (<%= @user.modClubs.count %>) 
            <span><% @user = User.find(params[:id]) %></span>
        </h1>
        <span><% @clubs.each do |club| %>
    
                    <%if club.is_moderator?(@user) %>
                        <span><%= image_tag(club.club_avatar.url(:thumb)) %>
                        &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to club.name, manage_club_path(path: club.path) %>
                        </span> 
                    <% end %>
                <% end %>
    <% else %>
        <br>
        <br>
        <h1>
            You don't have any club right now.
            <% if @user == current_user %>
                <% if current_user.admin? %>
                    <%= link_to "Create New Club", new_club_path %>
                <% else %>
                    <%= link_to "Click here to join one!", clubs_path %>
                <% end %>    
            <% end %>
        </h1>
    <% end %>
        
    </div>

</div>

app/views/users/moderator_invitations.html.erb
<% if @mod_requests.any? %>

<% @mod_requests.each do |mod_request| %>

    <% user = User.find(mod_request.inviting_user_id) %>
 <p>You've been invited to to become a mod for <%= mod_request.club.name %> invited by <%= user.name %> </p>
 <p><%= link_to "Click here to become a mod!" , update_modrequest_club_path(club_id: mod_request.club_id, path: mod_request.club.path, target_club_params: mod_request.club_id), method: :post %></p>
 


<% end %>

<% else %>

<h1>You do not have any invitations</h1>

<% end %>

app/views/users/my_clubs.html.erb
<div class="profile_ban">
    <h1>Your Clubs</h1>
        <span>
            <% if @user.memClubs.any? %>
              <% @clubs.each do |club| %>
                  <span><%= image_tag(club.club_avatar.url(:thumb)) %>
                  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to club.name, build_club_path(club) %>
                  </span> 
              <% end %>
            <% else %>
              <span>You are not a member of any clubs <%= link_to "Click here to join one!", clubs_path %></span>
            <% end %>
        </span>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, 'Create my account') %>

<h1 class="headings">
  Sign up
</h1>


  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
      
      <p>Have an account already? <%= link_to "Log In!", login_path %></p>
    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

 



<div class="row">      
      
      
         <% @user = User.find(params[:id]) %>
          <div class="avatar_edit">
            <%= image_tag(@user.avatar.url(:thumb)) %>
            <span class="username_tag">
              <h1><%= @user.name %></h1>
              <p>&emsp;</p>
            </span>
          </div>
          
    <% if logged_in? %>
      <% if @user==current_user %>
    <%= month_calendar events: @posts  do |date, post| %>
        <%= date.day %>
        <% post.each do |post| %>
            <div>
            <% if post.option =="isEvent" %>
                <% @club=post.club %>
                <% if @club.is_member?(current_user) %>
                    <%= link_to post.title, build_post_path(post) %>
                <%end%>
            <%end%>
            </div>
        <% end %>
    <%end%>
    <%end%>
    <%end%>
      <div class="profile_ban">
        <h1>Profile
        <span><% @user = User.find(params[:id]) %>
          <% if @user==current_user %>
          <%= link_to "Edit Profile", edit_user_path %> |
          <%= link_to "Moderator Invitations", moderator_invitations_user_path %> (<%= @user.mod_requests.count %>)
        <% end %></span></h1>
        <span>Email: <%= @user.email %></span>
        <span>First Name: <%= @user.firstname %></span>
        <span>Last Name: <%= @user.lastname %></span>
        <span>Gender: <%= @user.gender %></span>
        <span>Birthday: <%= @user.birthday %></span>
        <span>Phone Number: <%= @user.phone %></span>
        <span>Degree: <%= @user.degree %></span>
        <span>Major: <%= @user.major %></span>

      </div>
</div>