config/routes.rb
Rails.application.routes.draw do
 

  resources :users do
    member do
     get 'manage'
     get 'moderator_invitations'
     get 'my_clubs'
    end
  end
  
  
  resources :member_requests, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :clubs, only: [:new, :create, :index, :edit, :update]
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end

  root 'welcome#welcomepage'
  
  get 'welcome/home'
  get 'welcome/terms'
  get 'welcome/map'
  get 'welcome/privacy'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/help'
  get 'signup' =>'user#new'

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

 

  
  get 'commit' => 'clubs#new'
  get 'p/:path' => 'clubs#show', as: :view_club
  get 'p/:path/manage/members' => 'clubs#show_members', as: :manage_club_members
  get 'p/:path/manage/manage_requests' => 'clubs#manage_requests', as: :manage_requests
  get 'p/:path/manage' => 'clubs#manage', as: :manage_club
  get 'p/:path/manage/add_moderator' => 'clubs#add_moderator', as: :add_moderator_club
  post 'p/:path/manage/mod_request' => 'clubs#mod_request', as: :mod_request_club
  post 'p/:path/update_modrequest' => 'clubs#update_modrequest', as: :update_modrequest_club
  
  get 'p/:path/newpost' => 'posts#new', as: :new_club_post
  get 'p/:path/:post_id' => 'posts#show', as: :view_club_post

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  acts_as_votable
  belongs_to :user
  belongs_to :club
  has_many :comments, dependent: :destroy
  
  before_save :format_website_url
  before_save :scrape_with_grabbit

  
  scope :latest, -> { order(created_at: :desc) }
  scope :by_hot_score, -> { order(hotscore: :desc) }
  scope :five_days_ago, lambda { where("created_at >= :date", :date => 5.days.ago) }
  
  #mount_uploader :picture, PictureUploader
  #validates :url, :format => URI::regexp(%w(http https)), presence: false
  validates :context,  presence: true, length: { maximum: 5000 }
  validates :title,  presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :club_id, presence: true

  validates_presence_of :option, :if => ["true","false"]


  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  def is_owner?(user)
    user.id == user_id
  end
  

  
  private 
  
  def format_website_url
    unless url.blank?
      return if url.include?('http://') || url.include?('https://')
      self.url = "http://#{url}"
    end
  end
  
  def scrape_with_grabbit
    unless url.blank?
      data = Grabbit.url(url)
      #self.context = data.description 
      self.picture = data.images
    end
  end
  
  #def set_time_to_nil
    #if self.option == "true"
      #self.start_time = nil
    #end
  #end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :logged_in_user, except: :show
    before_action :set_post, only: [:edit, :update, :destroy, :upvote]
    #before_action :correct_user, only: [:edit]
    before_action :authorized_member?, only: :new
    layout 'post' , only: :show
    
    def new
        @club = nil
        @club = Club.by_path(params[:path]) if params[:path]
        @post = Post.new
    end
    
    def create
        #@club = Club.by_path(params[:post][:clubpath]) if params[:post][:clubpath]
        @club = Club.by_path(params[:club_path]) if params[:club_path]
        
        
        if @club.nil?
            flash[:danger] = 'ERROR: Could not find the specificed club'
            redirect_to root_path and return
        end
        
        unless @club.is_member?(current_user)
            flash[:danger] = "Only members can create posts."
            redirect_to build_club_path(@club) and return
        end
        
        
        @post = Post.new(post_params)
        @post.club_id = @club.id
        @post.user_id = current_user.id
        
        if @post.save
            flash[:success] = "Post created!"
            #the path for post#show is
            #p/:path/:post_id
            #redirect_to view_club_post_path(path: @post.club.path, post_id: @post.id)
            redirect_to build_post_path(@post)
        else
            render :new
        end
    end
    
    def show
        #because p/:path/:post_id = post#show
        #we cant do @post = Post.find(params[:id]) as :id is no longer defined
        @post = Post.where(id: params[:post_id]).first
        
        if @post.nil?
            flash[:danger] = 'ERROR: Post does not exist'
            redirect_to root_path and return
        end
    end
    
    def edit
        if @post.nil?
            flash[:danger] = 'ERROR: Post does not exist'
            redirect_to root_path and return
        end
        
        @club = @post.club
        redirect_to build_post_path(@post) unless @post.is_owner?(current_user)
    end
    
    def update
        if @post.nil?
            flash[:danger] = 'ERROR: Post does not exist'
            redirect_to root_path and return
        end
        
        unless @post.is_owner?(current_user)
            redirect_to build_post_path(@post) and return
        end
        
        if @post.update(post_params)
            flash[:success] = "Post Updated!"
            redirect_to build_post_path(@post)
        else
          render :edit
        end
    end
     
    def destroy
        @club = @post.club
        unless @post.is_owner?(current_user) || @club.is_moderator?(current_user)
            flash[:danger] = "You are not the owner of this post."
            redirect_to build_club_path(@club) and return
        end
        @post.destroy
        flash[:success] = "Post deleted"
        redirect_to build_club_path(@post.club)
    end
    
    def upvote
        @post.upvote_by current_user
        @post.hotscore = @post.get_upvotes.size
        @post.save
        redirect_to :back
    end


    private
    
    def post_params
        params.require(:post).permit(:context, :title, :url, :club_id, :image, :picture, :option, :start_time)
    end
    
    def authorized_member?

        @club = Club.by_path(params[:path]) if params[:path]
        
        if @club.nil?
            flash[:danger] = "Unable to find the specified club" 
            redirect_to clubs_path
        end
        
        unless @club.is_member?(current_user)
            flash[:danger] = "Only members can create posts."
            redirect_to build_club_path(@club)
        end
    end

    # unused
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      
      redirect_to root_url if @post.nil?
    end
    
    def set_post
        @post = Post.find(params[:id])
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :context %>
      <%= f.text_area :context, class: 'form-control', rows: "10" %>
    
      <%= f.label :url, 'Share a URL' %>
      <%= f.text_field :url, class: 'form-control' %>
      
       <b>This is a : </b>
      <br>
      
      
      <span class='radio-inline'>
           <%= f.label :option,  "Posts" %>
         
           <%= f.radio_button :option, "isPost", :checked => true %>
        </span>
          <br>
       <span class='radio-inline'>  
           <%= f.label :option, "Event" %>
           
            <%= f.radio_button :option, "isEvent", :onclick => 'render_partial("partial-area");'%>
      </span>
         <br>
         <br>
<script>
      $(document).ready(function(){
        $('input[type="radio"]').click(function(){
        if($(this).attr("value")=="isEvent"){
            $("#partial-area").show(); 
        }
        if($(this).attr("value")=="isPost"){
            $("#partial-area").hide();
        }
    });
});
</script>

<div id="partial-area" style = "display: none;">
    <%= f.label :start_time %>
    <span id = "time-select" style = "display: flex;">
        <%= f.datetime_select :start_time %>
    </span>
</div>      
      
      <%#= f.hidden_field :clubpath , :value => @club.path %> 
      <%#= f.text_field :clubpath, class: 'form-control' %>
      <%= hidden_field_tag :club_path, @club.path %>
      
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

  	<br>
      <%= f.submit "Create post", class: "btn btn-primary" %>

      
<% end %>

app/views/posts/_heading.html.erb
        <% if @post.picture?  %>
          <%= link_to (image_tag @post.picture), @post.url %>
        <% else %>
          <% if @post.image?  %>
          <%= link_to (image_tag @post.image.url), build_post_path(@post) %>
          <%end%>
        <%end%>
        
        <div class = "panel-body">
            <% if @post.url.blank? %>
                <h4><%= link_to raw(@post.title), build_post_path(@post)%></h4>
                <span class = "timestamp">
                  Posted By: <%= link_to @post.user.name, @post.user %>
                  <% if @post.option == "isEvent" %>
                  | <i style = "color: white; background-color: green">Event</i>
                  <% end %>
                  <br>
                </span>
            <%else%>
                <h4><%= link_to raw(@post.title), build_post_path(@post) %></h4>
                <span class = "timestamp">
                  Posted By: <%= link_to @post.user.name, @post.user %> | Has Shared a <%= link_to raw("Link"), @post.url%>
                  <% if @post.option == "isEvent" %>
                  | <i style = "color: white; background-color: green">Event</i>
                  <% end %>
                  <br>
                </span>
            <%end%>
            <span class="timestamp">
              <%= link_to "Comments", build_post_path(@post)%>  
                <% if logged_in? and @post.is_owner?(current_user) %>
                  | <%= link_to "Edit", edit_post_path(@post) %> 
                <% end %>
                <% if logged_in? and (current_user.modClubs.include?(@club) or @post.is_owner?(current_user)) %>
                  | <%= link_to "Delete", post_path(@post), method: :delete,
                                               data: { confirm: "You sure?" } %>
                <% end %>
              <br>
              Posted <%= time_ago_in_words(@post.created_at) %> ago.
            </span>
            
            <div class = "btn btn-group pull-right">
              <span class="glyphicon glyphicon-heart"></span>
              <%= @post.get_upvotes.size %>
            </div>

        </div>
 

app/views/posts/_heading2.html.erb
<div class = "box panel panel-default">
        <% if @post.picture?  %>
          <%= link_to (image_tag @post.picture), build_post_path(@post) %>
        <% else %>
          <% if @post.image?  %>
          <%= link_to (image_tag @post.image.url), build_post_path(@post) %>
          <%end%>
        <%end%>
        
        <div class = "panel-body">
            <% if @post.url.blank? %>
                <h4><%= link_to raw(@post.title), build_post_path(@post)%></h4>
                <span class = "timestamp">
                  Posted By: <%= link_to @post.user.name, @post.user %> | 
                  <%= link_to @post.club.name, build_club_path(@post.club) %>
                  <% if @post.option == "isEvent" %>
                  | <i style = "color: black; background-color: green">Event</i>
                  <% end %>
                  <br>
                </span>
            <%else%>
                <h4><%= link_to raw(@post.title), @post.url %></h4>
                <span class = "timestamp">
                  Posted By: <%= link_to @post.user.name, @post.user %> | Has Shared a <%= link_to raw("Link"), @post.url%>
                  <br>
                </span>
            <%end%>
            <span class="timestamp">
              <%= link_to "Comments", build_post_path(@post)%>  
                <% if logged_in? and @post.is_owner?(current_user) %>
                  | <%= link_to "Edit", edit_post_path(@post) %> 
                <% end %>
                <% if logged_in? and (current_user.modClubs.include?(@club) or @post.is_owner?(current_user)) %>
                  | <%= link_to "Delete", post_path(@post), method: :delete,
                                               data: { confirm: "You sure?" } %>
                <% end %>
              <br>
              Posted <%= time_ago_in_words(@post.created_at) %> ago.
            </span>
            
            <div class = "btn btn-group pull-right">
              <span class="glyphicon glyphicon-heart"></span>
              <%= @post.get_upvotes.size %>
            </div>

        </div>
</div>  

app/views/posts/_home.html.erb
        <% if @post.picture?  %>
          <%= link_to (image_tag @post.picture), build_post_path(@post) %>
        <% else %>
          <% if @post.image?  %>
          <%= link_to (image_tag @post.image.url), build_post_path(@post) %>
          <%end%>
        <%end%>
        
        <div class = "panel-body">
            <% if @post.url.blank? %>
                <h4><%= link_to raw(@post.title), build_post_path(@post)%></h4>
                <span class = "timestamp">
                   Posted By: <%= link_to @post.user.name, @post.user %> | 
                  <%= link_to @post.club.name, build_club_path(@post.club) %>
                  <% if @post.option == "isEvent" %>
                  | <i style = "color: white; background-color: green">Event</i>
                  <% end %>
                  <br>
                </span>
            <%else%>
                <h4><%= link_to raw(@post.title), @post.url %></h4>
                <span class = "timestamp">
                  Posted By: <%= link_to @post.user.name, @post.user %> | 
                  Has Shared a <%= link_to raw("Link"), @post.url%> |
                  <%= link_to @post.club.name, build_club_path(@post.club) %>
                  <% if @post.option == "isEvent" %>
                  | <i style = "color: white; background-color: green">Event</i>
                  <% end %>
                  <br>
                </span>
            <%end%>
            <span class="timestamp">
              <%= link_to "Comments", build_post_path(@post)%>  
                <% if logged_in? and @post.is_owner?(current_user) %>
                  | <%= link_to "Edit", edit_post_path(@post) %> 
                <% end %>
                <% if logged_in? and (current_user.modClubs.include?(@club) or @post.is_owner?(current_user)) %>
                  | <%= link_to "Delete", post_path(@post), method: :delete,
                                               data: { confirm: "You sure?" } %>
                <% end %>
              <br>
              Posted <%= time_ago_in_words(@post.created_at) %> ago.
            </span>
            
            <div class = "btn btn-group pull-right">
              <span class="glyphicon glyphicon-heart"></span>
              <%= @post.get_upvotes.size %>
            </div>

        </div>
 

app/views/posts/_show.html.erb
<div id = "post_show" class = "row" >
    <div class = "col-md-8 col-md-offset-2">
        <div class = "panel panel-default">
            <div class = "panel-body">
                <h4><%=@post.title%></h4>
            </div>
            <div class = "panel-heading pin_image">
                <% if @post.picture?  %>
                     <%= link_to (image_tag @post.picture), @post.url %>
                <% end %>
                <%= image_tag @post.image.url if @post.image? %>
            </div>
            
            <div class = "panel-body">
                <% if @post.option=="isEvent" %>
                    Event Date: <%=@post.start_time.year %>-<%=@post.start_time.month %>-<%=@post.start_time.day %> 
                <%end%>
                <p class = "description" style="white-space: pre-wrap; color:black;"><%=@post.context%></p>
            </div>
            
            <div class = "panel-footer">
                <div class = "row">
                    <div class = "col-md-6">
                        <p class = "user">Submitted by <%=@post.user.name%> </p>
                    </div>
                    <div class = "col-md-6">
                        <div class = "btn btn-group pull-right">
                            
                            <%= link_to like_post_path(@post), method: :put, class: "btn btn-default"  do %>
                                <span class="glyphicon glyphicon-heart"></span>
                                <%= @post.get_upvotes.size %>
                            <% end %>
                            
                            <% if logged_in? %>
                             <% if @post.is_owner?(current_user) %>
                                 <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
                                 <%= link_to "Delete Post", post_path(@post), method: :delete,
                                       data: { confirm: "You sure?" }, class: "btn btn-default" %>
                             <% end %>
                            <% end %> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@post, html: { multipart: true }) do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
              
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            
              <%= f.label :context %>
              <%= f.text_area :context, class: 'form-control', rows: "10" %>
            
              <%= f.label :url, 'Share a URL' %>
              <%= f.text_field :url, class: 'form-control' %>    
                
              <%= hidden_field_tag :club_path, @club.path %>
              
              <%= f.label :image %>
              <%= f.file_field :image, class: 'form-control' %>
        
              <%= f.submit "Update Post", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<h1 class="headings">
  <%=@club.name%> > New Post
</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
      <br>
  </div>
</div>

app/views/posts/show.html.erb
<h1 class="headings">
  <%= link_to @post.club.name, build_club_path(@post.club) %> > New Post
</h1>

<!-- render content of the post -->
<%= render 'show' %>

<% if logged_in? %>
    <%= render 'comments/form' %>
<% end %>

<!-- renders all the comments in the current post -->
<div class = "row">
    <div class="col-md-8 col-md-offset-2 ">
        <h3>Comments (<%= @post.comments.count %>)</h3>
        <ol class ="comments">
            <%#= render @post.comments %>
            <%= nested_messages @post.comments.arrange(order: 'created_at desc') %>
        </ol>
    </div>
</div>