config/routes.rb
Rails.application.routes.draw do
 

  resources :users do
    member do
     get 'manage'
     get 'moderator_invitations'
     get 'my_clubs'
    end
  end
  
  
  resources :member_requests, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :clubs, only: [:new, :create, :index, :edit, :update]
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end

  root 'welcome#welcomepage'
  
  get 'welcome/home'
  get 'welcome/terms'
  get 'welcome/map'
  get 'welcome/privacy'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/help'
  get 'signup' =>'user#new'

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

 

  
  get 'commit' => 'clubs#new'
  get 'p/:path' => 'clubs#show', as: :view_club
  get 'p/:path/manage/members' => 'clubs#show_members', as: :manage_club_members
  get 'p/:path/manage/manage_requests' => 'clubs#manage_requests', as: :manage_requests
  get 'p/:path/manage' => 'clubs#manage', as: :manage_club
  get 'p/:path/manage/add_moderator' => 'clubs#add_moderator', as: :add_moderator_club
  post 'p/:path/manage/mod_request' => 'clubs#mod_request', as: :mod_request_club
  post 'p/:path/update_modrequest' => 'clubs#update_modrequest', as: :update_modrequest_club
  
  get 'p/:path/newpost' => 'posts#new', as: :new_club_post
  get 'p/:path/:post_id' => 'posts#show', as: :view_club_post

end

app/views/layouts/_clubheader.html.erb
<% if @club.banner? %>

<!-- user banner -->
<div class="clubheader" style = "background-image: url(<%= @club.banner.url %>); height: 150px"></div>

<% else %>

<!-- default banner -->
<div class="clubheader" style = "background-image: url(/assets/banner.jpg)"><%= image_tag('GitClubLogo.png', id: "logo") %></div>

<% end %>

<nav class = "navbar navbar-inverse">
  <!--Contents of the nav are contained in a container-->
  <div class = "container">
    
    <!--The Name?-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "GitClub", welcome_home_path, class: "navbar-brand"%>
      
    </div>  
    
    <!--The remaining links -->
    <div class="collapse navbar-collapse" id="myNavbar">
      
      <!-- Left side links (Always display)-->
      <ul class = "nav navbar-nav">
          <li><%= link_to "All Clubs", clubs_path %></li>
          <% if logged_in? %>
            <li><%= link_to "My Clubs", my_clubs_user_path(current_user) %></li>
          <% end %>
      </ul>
      
      <!-- Right side links (Display if logged?)-->
      <ul class = "nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="avatar"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
          
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Club Management", manage_user_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> Sign Up'.html_safe, new_user_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, login_path %> </li>
        <% end %>
      </ul>
      
    </div>
    
  </div>
</nav>

app/views/layouts/_footer.html.erb
<!--
<footer class="footer">
  <small>
    Copyright &copy CMPT276 G4 - Fall 2015 All Rights reserved.
  </small>
  <nav>
    <ul>
      <li><%#= link_to "Terms",   welcome_terms_path %></li>
      <li><%#= link_to "Privacy", welcome_privacy_path %></li>
      <li><%#= link_to "Help",   welcome_help_path %></li>
      <li><%#= link_to "About",   welcome_about_path %></li>
      <li><%#= link_to "Contact", welcome_contact_path %></li>
    </ul>
  </nav>
</footer>
-->






<div id="footer">
  <nav>
    <div class = "container">
          <ul class = "footer-ul">
            | <%= link_to "Map and Direction", welcome_map_path, 'data-no-turbolink' => true %> |
            | <%= link_to "Terms",   welcome_terms_path %> |
            | <%= link_to "Privacy", welcome_privacy_path %> |
            | <%= link_to "Help",   welcome_help_path %> |
            | <%= link_to "About",   welcome_about_path %> |
            | <%= link_to "Contact", welcome_contact_path %> |
          </ul>
          <p class="footer-info">
              Copyright &copy CMPT276 G4 - Fall 2015 All Rights reserved.
          </p>
    </div>
  </nav>
</div>

app/views/layouts/_header.html.erb
<div class="clubheader" style = "background-image: url(/assets/banner.jpg)"><%= image_tag('GitClubLogo.png', id: "logo") %></div>

<nav class = "navbar navbar-inverse">
  <!--Contents of the nav are contained in a container-->
  <div class = "container">
    
    <!--The Name?-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "GitClub", welcome_home_path, class: "navbar-brand"%>
      
    </div>  
    
    <!--The remaining links -->
    <div class="collapse navbar-collapse" id="myNavbar">
      
      <!-- Left side links (Always display)-->
      <ul class = "nav navbar-nav">
          <li><%= link_to "All Clubs", clubs_path %></li>
          <% if logged_in? %>
            <li><%= link_to "My Clubs", my_clubs_user_path(current_user) %></li>
          <% end %>
      </ul>
      
      <!-- Right side links (Display if logged?)-->
      <ul class = "nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="avatar"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
          
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Club Management", manage_user_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> Sign Up'.html_safe, new_user_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, login_path %> </li>
        <% end %>
      </ul>
      
    </div>
    
  </div>
</nav>

app/views/layouts/_postheader.html.erb
<% if @post.club.banner? %>

<!-- user banner -->
<div class="clubheader" style = "background-image: url(<%= @post.club.banner.url %>); height: 150px"></div>

<% else %>

<!-- default banner -->
<div class="clubheader" style = "background-image: url(/assets/banner.jpg)"><%= image_tag('GitClubLogo.png', id: "logo") %></div>

<% end %>



<nav class = "navbar navbar-inverse">
  <!--Contents of the nav are contained in a container-->
  <div class = "container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "GitClub", welcome_home_path, class: "navbar-brand"%>
      
    </div>  
    
    <!--The remaining links -->
    <div class="collapse navbar-collapse" id="myNavbar">
      
      <!-- Left side links (Always display)-->
      <ul class = "nav navbar-nav">
          <li><%= link_to "All Clubs", clubs_path %></li>
          <% if logged_in? %>
            <li><%= link_to "My Clubs", my_clubs_user_path(current_user) %></li>
          <% end %>
      </ul>
      
      <!-- Right side links (Display if logged?)-->
      <ul class = "nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="avatar"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
          
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Club Management", manage_user_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> Sign Up'.html_safe, new_user_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, login_path %> </li>
        <% end %>
      </ul>
      
    </div>
    
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <div id="wrapper">
        <!-- header -->
        <%= render 'layouts/header' %>
        
        <!-- content -->
          <div class="container">
              <div id="body">
                <% flash.each do |message_type, message| %>
                  <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
                  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                <% end %>
                <%= yield %>
              </div>
          </div>
        
       <!-- footer -->
       <%= render 'layouts/footer' %>
        
        
    </div>
    
    
  </body>
</html>

app/views/layouts/club.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body class = "club" style = "background-image:url(<%= @club.background.url %>);">

    <div id="wrapper">
        <!-- header -->
        <%= render 'layouts/clubheader' %>
        
        <!-- content -->
          <div class="container">
              <div id="body">
                <% flash.each do |message_type, message| %>
                  <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
                  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                <% end %>
                <%= yield %>
              </div>
          </div>
        
       <!-- footer -->
       <%= render 'layouts/footer' %>
        
        
    </div>
    
    
  </body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body class = "club" style = "background-image:url(<%= @post.club.background.url %>);">

    <div id="wrapper">
        <!-- header -->
        <%= render 'layouts/postheader' %>
        
        <!-- content -->
          <div class="container" style = "background-color: white;">
              <div id="body">
                <% flash.each do |message_type, message| %>
                  <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
                  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                <% end %>
                <%= yield %>
              </div>
          </div>
        
       <!-- footer -->
       <%= render 'layouts/footer' %>
        
        
    </div>
    
    
  </body>
</html>